# Generated by Django 5.2.3 on 2025-07-12 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trauma_remove_userprofile_batch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlenderModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='blender_models/')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='trauma',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='api.trauma'),
        ),
    ]
